CREATE TABLE "Shop" (
	"Id" SMALLINT PRIMARY KEY,
	"Name" TEXT,
	"Address" TEXT,
	"PhoneNumber" TEXT,
	"IsActive" BOOLEAN
);
INSERT INTO "Shop" ("Id", "Name", "Address", "PhoneNumber", "IsActive")
VALUES
	(1, 'Тухачевского', 'ул. Тухачевского, 19/3', '8 (962) 010-05-77', TRUE),
	(2, 'ТРК «Галерея»', 'ул. Маршала Жукова, 8', '8 (962) 010-05-77', TRUE),
	(3, 'ЖК «Шоколад»', 'пер. Крупской, 29', '8 (962) 010-05-77', TRUE),
	(4, 'Кулакова', 'пер. Макарова, 22', '8 (962) 010-05-77', FALSE);

CREATE TABLE "Product" (
	"Id" UUID PRIMARY KEY,
	"Name" TEXT,
	"Description" TEXT,
	"Price" INTEGER
);

CREATE TABLE "ProductImage" (
	"Href" TEXT,
	"ProductId" UUID REFERENCES "Product" ("Id")
);

CREATE TABLE "ProductStock" (
	"ProductId" UUID REFERENCES "Product" ("Id"),
	"ShopId" SMALLINT REFERENCES "Shop" ("Id"),
	"Amount" SMALLINT
);

CREATE TABLE "Order" (
	"Id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	"CreatedDate" TIMESTAMP
);

CREATE TABLE "OrderProduct" (
	"OrderId" INTEGER REFERENCES "Order" ("Id"),
	"ProductId" UUID,
	"Amount" SMALLINT
);